# Generated by Django 5.1.1 on 2026-03-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bookword',
            options={'verbose_name': 'Слово в книге', 'verbose_name_plural': 'Слова в книге'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='uploaded_at',
        ),
    ]
