# Generated by Django 5.1.1 on 2026-03-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GermanWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('german_word', models.CharField(max_length=200, unique=True, verbose_name='Немецкое слово')),
                ('russian_translation', models.CharField(max_length=200, verbose_name='Перевод на русский')),
            ],
        ),
    ]
