# Generated by Django 5.1.1 on 2026-03-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('german_words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='germanword',
            name='frequency_score',
            field=models.FloatField(default=0.0, verbose_name='Частотность'),
        ),
        migrations.AlterField(
            model_name='germanword',
            name='german_word',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='germanword',
            name='russian_translation',
            field=models.TextField(),
        ),
    ]
